all: InstruccionesGenerales

InstruccionesGenerales:
	cat PASOS/PASO_0.txt

PASO_1:
	cat PASOS/PASO_1.txt

PASO_2:
	cat PASOS/PASO_2.txt

PASO_3:
	cat PASOS/PASO_3.txt

PASO_4:
	cat PASOS/PASO_4.txt

PASO_5:
	cat PASOS/PASO_5.txt

PASO_6:
	cat PASOS/PASO_6.txt

PASO_7:
	cat PASOS/PASO_7.txt

PASO_8:
	cat PASOS/PASO_8.txt
